---

# Vorgensweise:
# - evtl. docker compose installieren
# - Verzeichnis für docker-compose.yml und Mounts erstellen
# - 3 Container:
#   - Nextcloud
#   - nginx
#   - Datenbank
# - Konfiguration mittels docker-compose.yml
# - Container starten
#

- hosts: server
  become: yes

  tasks:
# - docker installieren
#   - aus den Paketquellen!
#   - neueste Version nach Doku? -> evtl. falls Paketversion nicht kompatibel
  - name: Docker aus den Standard Debian Paketquellen installieren
    apt:
      pkg:
      - docker 
      - docker-engine 
      - docker.io 
      - containerd 
      - runc
      state: present

