---

# Vorgensweise:
# - evtl. docker compose installieren
# - 3 Container:
#   - Nextcloud
#   - nginx
#   - Datenbank
# - Konfiguration mittels docker-compose.yml
# - Container starten
#

- hosts: server
  become: yes

  tasks:
  # - docker installieren
  #   - aus den Paketquellen!
  #   - neueste Version nach Doku? -> evtl. falls Paketversion nicht kompatibel
  - name: Docker aus den Standard Debian Paketquellen installieren
    apt:
      pkg:
      - docker 
      - docker.io 
      - containerd 
      - runc
      state: present

  - name: Verzeichnis für docker-compose.yml, mounts und Dateien erstellen
    file:
      path: /srv/docker/nextcloud
      state: directory
      mode: '0755'
