---

# Vorgensweise:
# - Container starten
#

- hosts: server
  become: yes
  vars:
    nextcloud_dir: /srv/docker/nextcloud
  tasks:
  # - docker installieren
  #   - aus den Paketquellen!
  #   - neueste Version nach Doku? -> evtl. falls Paketversion nicht kompatibel
  # - evtl. docker compose installieren
  - name: Docker und docker-compose aus den Standard Debian Paketquellen installieren
    apt:
      pkg:
      - docker 
      - docker.io 
      - containerd 
      - runc
      - docker-compose
      state: present

  - name: Verzeichnis für docker-compose.yml, mounts und Dateien erstellen
    file:
      path: '{{ nextcloud_dir }}'
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: docker-compose.yml auf Server kopieren
    copy:
      src: docker-compose.yml
      dest: '{{ nextcloud_dir }}'
      owner: root
      group: root
      mode: '0644'

  - name: nginx.conf auf Server kopieren
    copy:
      src: nginx.conf
      dest: '{{ nextcloud_dir }}'
      owner: root
      group: root
      mode: '0644'

