= Dokumentation LF10b Freiburg

== Grundlegende Kommandos

* `cd` - Wechselt in ein Verzeichnis
* `ls` - Listet den Inhalt des aktuellen Verzeichnisses
* `ls -a` - Listet den Inhalt des aktuellen Verzeichnisses, inkl. versteckter Dateien
* `ls -l` - Listet den Inhalt des aktuellen Verzeichnisses, ausführliche Schreibweise/Informationen
* `man <kommando>` - Öffnet die Handbuchseite/Hilfe von `<kommando>`
* `pwd` - Print Working Directory, zeigt den absoluten Pfad des Verzeichnisses an, in dem man sich gerade befindet
* `date` - zeigt aktuelles Datum/Uhrzeit, Ausgabe kann formatiert werden
* `ip address` / `ip a` - Konfiguration der Netzwerkschnittstellen, z.B. zur Ermittlung der IP-Adresse
* `touch` - erstellt leere Dateien
* `mkdir` - erstellt ein neues Verzeichnis
* `cp <quelle> <ziel>` - kopiert <quelle> nach <ziel>
* `mv <quelle> <ziel>` - verschiebt <quelle> nach <ziel>
* `rm <datei>` - löscht `<datei>`
* Option `-r` - beim Kopieren und Löschen: auch Verzeichnisse, nicht nur Dateien

== Pfadangaben

* relativer Pfad::Weg/Pfad vom aktuellen Verzeichnis zum Ziel
* absoluter Pfad::Weg/Pfad vom Wurzel-Verzeichnis (`/`) zum Ziel

== Tastenkürzel

=== Manpage

* `q` Manpage verlassen
* `/` in der Manpage suchen

=== Shell

* `STRG+L` / `clear` -  Bildschirm leeren (wie `cls`)
* `STRG+C` - sowas wie _Abbruch_
* `STRG+D` / `exit` - Shell schließen
* Pfeil-nach-oben: rückwärts durch die zuletzt eingegebenen Befehle blättern (`history`)

== Git

* Git ist ein Programm zur Versionskontrolle (VCS - Version Control Software)
* entwickelt von Linux Torvalds
* ermöglicht u.a. bestimmte Zustände der Software als eine Art _Snapshot_ zu sichern

== Aliase

* `alias ll='ls -l'` - durch Eingabe von `ll` wird das Kommando `ls -l` ausgeführt 
* Werden Aliase nur auf der Shell definiert, sind sie auch nur für die aktuelle Shell-Session gülitg
* Sollen sie permanent gespeichert werden, müssen sie in eine Datei eingetragen werden, z.B. `~/.bashrc` oder `~/.bash_aliases`

== Dateioperationen "sicherer" machen

* für `cp`, `mv` und `rm` gibt es die Option `-i`, so dass eine Nachfrage erscheint, falls das Ziel vorhanden ist

== Wildcards/Platzhalter

* `*` - steht für ein beliebiges Zeichen, dass beliebig oft vorkommen darf
* `?` - steht für ein beliebiges Zeichen, dass exakt einmal vorkommt

 # lösche die Dateien file1.txt,  files.txt, file10basdlkjalskdjfakjlkfjaf.txt usw.
 rm -r file*.txt

 # lösche die Dateien file1.txt,  files.txt, aber nicht file10basdlkjalskdjfakjlkfjaf.txt usw.
 rm -r file?.txt

== FHS - Filesystem Hierarchy Standard

Einige der wichtigsten Verzeichnisse unter `/`:

* `/boot` - ausführbares Kernelimage, Konfigutationsdateien des Bootloaders
* `/bin` - von regulären Benutzern ausführbare Dateien
* `/sbin` - nur von root ausführbare Dateien
* `/etc` - systemweiten Konfigurationsdateien
* `/dev` - Gerätedateien (Speichermedien, virtuelle Geräte ...)
* `/var` - variable Dateien (Log-Dateien, E-Mails, unter Debian auch Dateien die ein Webservers ausliefert)
* `/proc` - hier werden Informationen über jeden laufenden Prozess abgelegt. Existiert nur im RAM, weitere Infos über z.B. CPUs etc.
* `/sys` - Erweiterung von `/proc`
* `/home` - Verzeichnis, in dem sich die Heimatverzeichnisse der regulären Benutzer befinden
* `/root` - Heimatverzeichnis des Benutzers `root`

== Standardkanäle

* `stdin` - Standardeingabekanal (`0`)
* `stout` - Standardausgabekanal (`1`)
* `stderr` - Standardfehlerkanal (`2`)

== Redirects / Umleitungen

* `echo huhu 1> ausgabekanal.txt` -> in `ausgabekanal.txt` steht `huhu`
* `echo huhu > ausgabekanal.txt` -> in `ausgabekanal.txt` steht `huhu`
* `ls -l /etc > ausgabe-etc.txt` -> in `ausgabe-etc.txt` steht die Ausgabe von `ls -l /etc`
* `ls -l gibtsnicht 2> fehler.txt` -> (das Verzeichnis `gitsnicht` existiert nicht: in `fehler.txt` steht eine entsprechende Fehlermelung

Mit den Redirect Operatoren `>` und `>>` können wir Ausgaben in *Dateien* umleiten.

Mit `>` wird der Inhalt der Datei überschrieben, mit `>>` angehängt.

Mit `<` kann der Inhalt einer Datei an den Eingabekanal eines Kommandos umgeleitet werden.

 mail -s "Ein Betreff" tux@linux.com < mailtext.txt

== Kommandopipelines

Mit der Pipe `|` wird der Ausgabekanal von `kommando1` mit dem Eingabekanal von `kommanod2` verbunden. So können Kommandos miteinander verbunden werden.

 kommando 1 | kommando 2

Die Ausgabe von `ls -l` mit dem Pager `less` öffnen, so dass wir darin blättern und suchen können:

 ls -l /etc | less

Login Shell des Users `root` ausgeben (`/bin/bash`):

 grep root /etc/passwd | cut -d: -f7 

== Benutzerverwaltung

== Dateizugehörigkeiten ändern

Benutzer und Gruppe ändern:

 chown user:group datei

nur Benutzer ändern:

 chown user datei

nur Gruppe ändern:

 chown :group datei
 chgrp group datei

== Dateiberechtigungen

   u     g     o
  user group other
 -rw-  r--   r--    1 tux tux    0 Apr 20 09:49 new.txt

3 Symbole für Berechtigungen:

 r: read -> lesen
 w: write -> schreiben
 x: execute -> ausführen

=== Symbolische Rechtevergabe

 chmod o-r datei
 chmod u+w datei
 chmod o-rw datei
 chmod g=rwx datei

Sinnvoll, wenn nur einzelne Rechte hinzugefügt/entfernt werden sollen, unabhängig von anderen bestehenden Rechten:

 chmod u+x script

=== Oktale Rechtevergabe

 r: read    -> 4
 w: write   -> 2
 x: execute -> 1
 -: kein Recht -> 0
 
 chmod 640 new.txt 

Diese Rechtevergabe eignet sich, wenn Rechte absolut gesetzt werden sollen, für User, Group und Others gleichzeitig:

 chmod 600 secret.txt

=== Herkunft Oktale Rechtevergabe

----
 4 : 100
 2 : 010
 1 : 001

 7 : 111
 6 : 110

 111110100
 rwxrw-r-- datei
----

== Paketverwaltung











